food_cloud/urls.py
from django.urls import path
from django.urls import include
from django.conf import settings
from food_cloud import views
from django.conf.urls.static import static
app_name = "food_cloud"

urlpatterns = [
    path('', views.index, name='index'),
    path('index/', views.index, name='index'),
    path('index_restaurant/', views.index_restaurant, name='index_restaurant'),
    path('register_choice/', views.register_choice, name='register_choice'),
    path('register/', views.register, name='register'),
    path('register_restaurant/', views.register_restaurant,
         name='register_restaurant'),
    path('login_choice/', views.login_choice, name='login_choice'),
    path('login/', views.user_login, name='login'),
    path('login_restaurant/', views.restaurant_login, name='login_restaurant'),
    path('add_order/<meal_slug>/<meal_restaurant>/',
         views.add_order, name='add_order'),
    path('add_favourite/<meal_name_slug>',
         views.add_favourite, name='add_favourite'),
    path('remove_favourite/<meal_name_slug>',
         views.remove_favourite, name='remove_favourite'),
    path('logout/', views.user_logout, name='logout'),
    path('about/', views.about, name='about'),
    path('about_restaurant/', views.about_restaurant, name='about_restaurant'),
    path('contact/', views.contact, name='contact'),
    path('contact_restaurant/', views.contact_restaurant,
         name='contact_restaurant'),
    path('my_account/', views.my_account, name='my_account'),
    path('profile/<username>/', views.ProfileView.as_view(), name='profile'),
    path('profile_restaurant/<username>/',
         views.ProfileView_restaurant.as_view(), name='profile_restaurant'),
    path('add_meal/', views.add_meal, name='add_meal'),
    path('meal/<slug:meal_name_slug>/', views.show_meal, name='show_meal'),
    path('restaurant/<slug:restaurant_name_slug>/',
         views.show_restaurant, name='show_restaurant'),
    path('search/', views.search, name='search'),
    path('search_restaurant/', views.search_restaurant, name='search_restaurant'),
    path('search_restaurants/',
         views.search_restaurants, name='search_restaurants'),
    path('restricted/', views.restricted, name='restricted'),
    path('rate_meal/<meal_slug>/<meal_restaurant>/',
         views.rate_meal, name='rate_meal'),
    path('get_favourite_status/<meal_slug>/',
         views.get_favourite_status, name='get_restaurant_status'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

team_project_food_cloud/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static
from food_cloud import views

urlpatterns = [
    path('admin/', admin.site.urls),
	path('', views.index, name='index'),
	path('food_cloud/', include('food_cloud.urls')),
	#path('accounts/', include('registration.backends.simple.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

food_cloud/forms.py
from django import forms
from food_cloud.models import *
from django.contrib.auth.models import User
from food_cloud.models import *
from django.contrib.auth.forms import UserCreationForm


class MealForm(forms.ModelForm):
    meal_name = forms.CharField(
        max_length=30, help_text="Please enter the meal name.")
    description = forms.CharField(
        max_length=200, help_text="Please enter the meal description.", required=False)
    price = forms.FloatField(
        help_text="Please enter the meal price.", min_value=0.01)
    picture = forms.ImageField(
        required=False, help_text="Please upload a picture.")
    restaurant_slug = forms.SlugField(widget = forms.HiddenInput(), required=False, help_text="Please enter the slug of your restaurant.")

    def __init__(self, *args, **kwargs):
        self.restaurant_slug = kwargs.pop('restaurant_slug', None)
        super(MealForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        obj = super(MealForm, self).save(commit=commit)
        obj.restaurant_slug = self.restaurant_slug
        if commit:
            obj.save()
        return obj

    class Meta:
        model = Meal
        exclude = ('average_rating', 'meal_id', 'customers',
                   'customer_favourites', 'num_orders', 'slug')


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class RestaurantForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password',)


class RestaurantProfileForm(forms.ModelForm):
    class Meta:
        model = RestaurantProfile
        fields = ('type',)

food_cloud/views.py
from django.shortcuts import render
from django.template import RequestContext
from django.http import HttpResponse, JsonResponse
from food_cloud.models import *
from food_cloud.forms import *
from django.shortcuts import redirect
from django.urls import reverse, reverse_lazy
from food_cloud.forms import *
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from datetime import datetime
from food_cloud.bing_search import run_query
from django.contrib.auth.models import User
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.template.defaultfilters import slugify


def index(request):
	context_dict = get_context_dict(request)
	context_dict['restaurants'] = RestaurantProfile.objects.order_by(
		'-average_rating')[:5]
	context_dict['meals'] = Meal.objects.order_by(
		'-num_orders', '-average_rating')[:5]

	response = render(request, 'food_cloud/index.html', context=context_dict)
	return response


def index_restaurant(request):
	context_dict = {}

	meal_list = Meal.objects.order_by('meal_name')

	context_dict = {}
	context_dict['meals'] = meal_list

	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']

	response = render(
		request, 'food_cloud/index_restaurant.html', context=context_dict)
	return response


def register_choice(request):
	context_dict = {}
	response = render(
		request, 'food_cloud/register_choice.html', context=context_dict)
	return response


def login_choice(request):
	context_dict = {}
	response = render(request, 'food_cloud/login_choice.html',
					  context=context_dict)
	return response


def register(request):
	registered = False

	if request.method == 'POST':
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			if 'picture' in request.FILES:
				profile.picture = request.FILES['picture']

			profile.save()
			registered = True
			user_login(request)
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = UserForm()
		profile_form = UserProfileForm()
	return render(request, 'food_cloud/register.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def register_restaurant(request):
	registered = False

	if request.method == 'POST':
		user_form = RestaurantForm(request.POST)
		profile_form = RestaurantProfileForm(request.POST)

		if user_form.is_valid() and profile_form.is_valid():
			user = user_form.save()
			user.set_password(user.password)
			user.save()
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			registered = True
			restaurant_login(request)
		else:
			print(user_form.errors, profile_form.errors)
	else:
		user_form = RestaurantForm()
		profile_form = RestaurantProfileForm()
	return render(request, 'food_cloud/register_restaurant.html', context={'user_form': user_form, 'profile_form': profile_form, 'registered': registered})


def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				try:
					customer = UserProfile.objects.get(user=user)
				except UserProfile.DoesNotExist:
					return redirect(reverse('food_cloud:login_restaurant'))
				login(request, user)
				return redirect(reverse('food_cloud:index'))
			else:
				return HttpResponse("Your food_cloud account is disabled.")
		else:
			print(f"Invalid login details: {username}, {password}")
			return HttpResponse("Invalid login details supplied.")
	else:
		return render(request, 'food_cloud/login.html')


def restaurant_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')
		user = authenticate(username=username, password=password)
		if user:
			if user.is_active:
				try:
					restaurant = RestaurantProfile.objects.get(user=user)
				except RestaurantProfile.DoesNotExist:
					return redirect(reverse('food_cloud:login'))
				login(request, user)
				return redirect(reverse('food_cloud:index_restaurant'))
			else:
				return HttpResponse("Your food_cloud account is disabled.")
		else:
			print(f"Invalid login details: {username}, {password}")
			return HttpResponse("Invalid login details supplied.")
	else:
		return render(request, 'food_cloud/login_restaurant.html')


@login_required
def user_logout(request):
	logout(request)
	return redirect(reverse('food_cloud:index'))


class ProfileView(View):
	def get_user_details(self, username):
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			return None
		user_profile = UserProfile.objects.get_or_create(user=user)[0]
		form = UserProfileForm(
			{'picture': user_profile.picture, 'isRestaurant': user_profile.isRestaurant})
		return (user, user_profile, form)

	@method_decorator(login_required)
	def get(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('food_cloud:index'))
		context_dict = {'user_profile': user_profile,
						'selected_user': user,
						'form': form}
		return render(request, 'food_cloud/profile.html', context_dict)

	@method_decorator(login_required)
	def post(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('food_cloud:index'))
		form = UserProfileForm(
			request.POST, request.FILES, instance=user_profile)
		if form.is_valid():
			form.save(commit=True)
			return redirect('food_cloud:profile', user.username)
		else:
			print(form.errors)
		context_dict = {'user_profile': user_profile,
						'selected_user': user,
						'form': form}
		return render(request, 'food_cloud/profile.html', context_dict)


class ProfileView_restaurant(View):
	def get_user_details(self, username):
		try:
			user = User.objects.get(username=username)
		except User.DoesNotExist:
			return None
		user_profile = RestaurantProfile.objects.get_or_create(user=user)[0]
		form = RestaurantProfileForm({'average_rating': user_profile.average_rating,
									  'type': user_profile.type, 'isRestaurant': user_profile.isRestaurant})
		return (user, user_profile, form)

	@method_decorator(login_required)
	def get(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('food_cloud:index_restaurant'))
		context_dict = {'user_profile': user_profile,
						'selected_user': user,
						'form': form}
		return render(request, 'food_cloud/profile_restaurant.html', context_dict)

	@method_decorator(login_required)
	def post(self, request, username):
		try:
			(user, user_profile, form) = self.get_user_details(username)
		except TypeError:
			return redirect(reverse('food_cloud:index_restaurant'))
		form = RestaurantProfileForm(
			request.POST, request.FILES, instance=user_profile)
		if form.is_valid():
			form.save(commit=True)
			return redirect('food_cloud:profile_restaurant', user.username)
		else:
			print(form.errors)
		context_dict = {'user_profile': user_profile,
						'selected_user': user,
						'form': form}
		return render(request, 'food_cloud/profile_restaurant.html', context_dict)


def about(request):
	context_dict = {}
	context_dict['boldmessage'] = 'This project was put together by Krasimir Ivanov, Jude Campbell, Olalekan Akala and Peter Rabai'
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(request, 'food_cloud/about.html', context=context_dict)
	return response


def about_restaurant(request):
	context_dict = {}
	context_dict['boldmessage'] = 'This project was put together by Krasimir Ivanov, Jude Campbell, Olalekan Akala and Peter Rabai'
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(
		request, 'food_cloud/about_restaurant.html', context=context_dict)
	return response


def contact(request):
	context_dict = {}
	context_dict['boldmessage'] = 'Contact us page(WIP)'
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(request, 'food_cloud/contact.html', context=context_dict)
	return response


def contact_restaurant(request):
	context_dict = {}
	context_dict['boldmessage'] = 'Contact us page(WIP)'
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(
		request, 'food_cloud/contact_restaurant.html', context=context_dict)
	return response


def my_account(request):
	context_dict = {}
	context_dict['boldmessage'] = 'my_account(WIP)'
	visitor_cookie_handler(request)
	context_dict['visits'] = request.session['visits']
	response = render(request, 'food_cloud/my_account.html',
					  context=context_dict)
	return response


def add_meal(request):
	user = request.user
	form = MealForm()
	restaurant = RestaurantProfile.objects.get_or_create(user=user)
	restaurant_slug = slugify(request.user.username)
	if request.method == 'POST':
		form = MealForm(request.POST)
		if form.is_valid():
			candidate=form.save(commit=False)
			candidate.restaurant_slug=slugify(request.user.username)
			candidate.save()
			return redirect('/food_cloud/index_restaurant/')
		else:
			print(form.errors)
	return render(request, 'food_cloud/add_meal.html', {'form': form})


def search(request):
	result_list = []
	query = ""
	if request.method == 'POST':
		query = request.POST['query'].strip()
		if query:
			result_list = run_query(query)
	print("DEBUG query=" + query)
	return render(request, 'food_cloud/search.html', {'result_list': result_list, 'query': query})

templates/food_cloud/about.html
{% extends 'food_cloud/base.html' %}
{% load staticfiles %}

{% block title_block %}
	<!--Title block -->
	About
{% endblock %}

{% block body_block %}
	<!--Body block -->
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">About</h1>
				<div>
					<strong>{{ boldmessage }}</strong>
				</div>
			</div>
		</div>
		
		<!-- <div> -->
			<!-- <img src="{% static 'images/food_cloud.jpg' %}" alt="Picture of food_cloud" /> -->
			<!-- <img src="{{MEDIA_URL}}/cat.jpg" alt="Picture of Cat."/> -->
		<!-- </div> -->
		<!-- <div> -->
		<!-- You have visited this page {{ visits }} times. -->
		<!-- </div> -->
{% endblock %}

templates/food_cloud/add_category.html
{% extends 'food_cloud/base.html' %}
{% load staticfiles %}

{% block title_block %}
	<!--Title block -->
	Add Category
{% endblock %}

{% block body_block %}
	<!--Body block -->
	<div class="jumbotron p-4">
		<div class="container">
			<h1 class="jumbotron-heading">Add a category</h1>
		</div>
	</div>
		
	<div class="container">
		<div class="row">
			<form role="form" id="category_form" method="post" action="{% url 'food_cloud:add_category' %}">
			{% csrf_token %}
			{% for hidden in form.hidden_fields %}
				{{ hidden }}
			{% endfor %}
			{% for field in form.visible_fields %}
				{{ field.errors }}
				{{ field.help_text }}<br />
				<p class="col-25"> {{ field.label_tag}} </p> <br />
                                <p class="col-75"> {{ field }} </p> <br />
				<div class="p-2"></div>
			{% endfor %}
				<br />
				<button class="btn btn-primary" type="submit" name="submit">
					Create Category
				</button>
				<div class="p-5"></div>
			</form>
		</div>
	</div>
		
		<div>
			<form id="category_form" method="post" action="/food_cloud/add_category/">
				{% csrf_token %}
				{% for hidden in form.hidden_fields %}
					{{ hidden }}
				{% endfor %}
				{% for field in form.visible_fields %}
					{{ field.errors }}
					{{ field.help_text }}
					{{ field }}
				{% endfor %}
				<input type="submit" name="submit" value="Create Category" />
			</form>
		</div>
{% endblock %}

templates/food_cloud/categories.html
{% load food_cloud_template_tags %}
<ul class="nav flex-column">
{% if categories %}
	{% for c in categories %}
	{% if c == current_category %}
		<li class="nav-item">
		<a class="nav-link active" href="{% url 'food_cloud:show_category' c.slug %}">
			<span data-feather="archive"></span>{{ c.name }}
		</a>
		</li>
	{% else %}
		<li class="nav-item">
		<a class="nav-link" href="{% url 'food_cloud:show_category' c.slug %}">
		<span data-feather="archive"></span>{{ c.name }}
		</a>
		</li>
	{% endif %}
	{% endfor %}
{% else %}
	<li class="nav-item">There are no categories present.</li>
{% endif %}
</ul>

templates/food_cloud/contact.html
{% extends 'food_cloud/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Contact
{% endblock %}

{% block body_block %}
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">Contact</h1>
				<div>
					Food Cloud
				</div>
				<div>
					University of Glasgow
				</div>
				<div>
					pkovacs92.pythonanywhere.com
				</div>
				<div>
					Tel.:0123456789
				</div>
				<div>
					Email: enquiries@food_cloud.com
				</div>
				<div>
					03/04/2020
				</div>
			</div>
		</div>
{% endblock %}

templates/food_cloud/contact_restaurant.html
{% extends 'food_cloud/base_restaurant.html' %}
{% load staticfiles %}

{% block title_block %}
	Contact
{% endblock %}

{% block body_block %}
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">Contact</h1>
				<div>
					Food Cloud
				</div>
				<div>
					University of Glasgow
				</div>
				<div>
					pkovacs92.pythonanywhere.com
				</div>
				<div>
					Tel.:0123456789
				</div>
				<div>
					Email: enquiries@food_cloud.com
				</div>
				<div>
					03/04/2020
				</div>
			</div>
		</div>
{% endblock %}

templates/food_cloud/index_restaurant.html
<!-- saved from url=(0133)https://www.pythonanywhere.com/user/pkovacs92/files/home/pkovacs92/team_project_food_cloud/templates/food_cloud/index_restaurant.html -->
<html><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"></head><body>{% extends 'food_cloud/base_restaurant.html' %}
{% load staticfiles %}

{% block title_block %}
	Homepage
{% endblock %}

{% block body_block %}
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
</head>	

		<div class="jumbotron p-2">
			<div class="container">
				<h1 class="jumbotron-heading">food_cloud says...</h1>
				<div>
					<h2 class="h2">
						Welcome to Food Cloud - Home for all Foodies
					</h2>
				</div>
			</div>
		</div>
		
		{% if user.is_authenticated %}
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-6">
					<div class="card mb-4">
						<div class="card-body">
							<h2>Available meals</h2>
							<p class="card-text">
							{% if meals %}
							</p><ul class="list-group">
							{% for meal in meals %}
								<li class="list-group-item">
									<ul class="list-group">
										<img src={{ meal.picture }} />
										<li class="list-group-item">{{ meal.meal_name }}</li>
										<li class="list-group-item">£{{ meal.price }}</li>
										<li class="list-group-item">{{ meal.description }}</li>
									</ul>
								</li>
							{% endfor %}
							</ul>
							{% else %}
							<strong>There are no meals present.</strong>
							{% endif %}
							<p></p>
						</div>
					</div>
				</div>
				
<!-- 				<div class="col-md-6">
					<div class="card mb-4">
						<div class="card-body">
							<h2>Available meals</h2>
							<p class="card-text">
							{% if meals %}
							</p><ul class="list-group">
							{% for meal in meals %}
								<li class="list-group-item">
									<ul class="list-group">
										<img src={{ meal.picture }} />
										<li class="list-group-item">{{ meal.meal_name }}</li>
										<li class="list-group-item">£{{ meal.price }}</li>
										<li class="list-group-item">{{ meal.description }}</li>
									</ul>
								</li>
							{% endfor %}
							</ul>
							{% else %}
							<strong>There are no meals present.</strong>
							{% endif %}
							<p></p>
						</div>
					</div>
				</div> -->
			</div>
		</div>
		{% else %}
			<strong>No restaurant logged in!</strong>
		{% endif %}
{% endblock %}
</body></html>

templates/food_cloud/meals.html
{% load food_cloud_template_tags %}
<ul class="nav flex-column">
{% if meals %}
	{% for c in meals %}
	{% if c == current_meal %}
		<li class="nav-item">
		<a class="nav-link active" href="{% url 'food_cloud:show_meal' c.slug %}">
			<span data-feather="archive"></span>{{ c.meal_name }}
		</a>
		</li>
	{% else %}
		<li class="nav-item">
		<a class="nav-link" href="{% url 'food_cloud:show_meal' c.slug %}">
		<span data-feather="archive"></span>{{ c.meal_name }}
		</a>
		</li>
	{% endif %}
	{% endfor %}
{% else %}
	<li class="nav-item">There are no meals present.</li>
{% endif %}
</ul>

templates/food_cloud/register_restaurant.html
{% extends 'food_cloud/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Register as Restaurant
{% endblock %}

{% block body_block %}
		<div class="jumbotron p-4">
			<div class="container">
				<h1 class="jumbotron-heading">Register as Restaurant</h1>
			</div>
		</div>
		
	{% if registered %}
	<body>
        <header>
            <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark p-0">                
                <div class="collapse navbar-collapse" id="navbarCollapse">
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item"><a class="nav-link" href="{% url 'food_cloud:index_restaurant' %}">Home</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'food_cloud:about_restaurant' %}">About</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'food_cloud:contact_restaurant' %}">Contact</a></li>
						<!-- <li class="nav-item "><a class="nav-link" href="{% url 'food_cloud:search_restaurant' %}">Search</a></li> -->
                        {% if user.is_authenticated %}
                        <!-- <li class="nav-item "><a class="nav-link" href="{% url 'food_cloud:restricted' %}">Restricted</a></li> -->
                        <li class="nav-item"><a class="nav-link" href="{% url 'food_cloud:logout' %}?next=/food_cloud/">Logout</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'food_cloud:add_meal' %}">Add Meal</a></li>
                        {% else %}
                        <li class="nav-item"><a class="nav-link" href="{% url 'food_cloud:register_choice' %}">Register</a></li>
                        <li class="nav-item "><a class="nav-link" href="{% url 'food_cloud:login_choice' %}">Login</a></li>
                        {% endif %}
                    </ul>
					<ul class="nav navbar-nav navbar-right">
						{% if user.is_authenticated %}
							<li class="nav-item"><a class="nav-link" href="{% url 'food_cloud:profile_restaurant' user.username %}">Account: {{ user.username }}</a></li>
						{% endif %}
					</ul>
                </div>
            </nav>
        </header>
	</body>
		food_cloud says: <strong>thank you for registering!</strong>
		<a href="{% url 'food_cloud:index_restaurant' %}">Return to the homepage.</a><br />
	{% else %}
	<form id="user_form" method="post" action="{% url 'food_cloud:register_restaurant' %}"
		enctype="multipart/form-data">
		{% csrf_token %}
		{{ user_form.as_p }}
		{{ profile_form.as_p }}
		<input type="submit" name="submit" value="Register" />
	</form>
	{% endif %}
{% endblock %}

templates/food_cloud/restaurant.html
{% extends 'food_cloud/base.html' %}
{% load staticfiles %}

{% block title_block %}

{% if restaurant %}
{{ restaurant.name }}
{% else %}
Unknown Restaurant
{% endif %}

{% endblock %}

{% block body_block %}

<div class="jumbotron p-4">
	<div class="container">
		{% if restaurant %}
		<h1>{{ restaurant.restaurant_name }}</h1>
		<h1>{{ restaurant.description }}</h1>
		{% else %}
		The specified restaurant does not exist.
		{% endif %}
	</div>
</div>


<div class="col-md-8 offset-md-3">
	<div class="card mb-8">
		<div class="card-body">
			<h2>Featured Meals</h2>
			<p class="card-text">
				<ul class="list-group">
					{% for meal in not_favourites %}
					<div class="row">
						<p class="col-8"><img src={{ meal.picture }} /></p>
						<p class="col-8">{{ meal.meal_name }}</p>
						<p class="col-8">{{ meal.price }}</p>
						<a href="" onclick="return false;" class="col-3"><span class="order_button"
								href="{% url 'food_cloud:add_order' meal.slug meal.restaurant_slug %}">Order</span></a>
						<a href="{% url 'food_cloud:add_favourite' meal.slug %}"
							class="col-3">Favourite</a>
					</div>
					<div class="row">
						<p class="col-12">{{ meal.description }}</p>
					</div>
					{% endfor %}
					{% for meal in favourites %}
					<div class="row">
						<p class="col-8"><img src={{ meal.meal.picture }}/></p>
						<p class="col-8">{{ meal.meal.meal_name }}</p>
						<p class="col-8">{{ meal.meal.price }}</p>
						<a href="" onclick="return false;"
								class="col-3"><span class="order_button"
									href="{% url 'food_cloud:add_order' meal.meal.slug meal.meal.restaurant_slug %}">Order</span></a>

						<a href="{% url 'food_cloud:remove_favourite' meal.meal.slug %}"
							class="col-3">Unfavourite</a>
					</div>
					<div class="row">
						<p class="col-12">{{ meal.meal.description }}</p>
					</div>
					{% endfor %}
				</ul>
			</p>
		</div>
	</div>
</div>

{% block extrajs %}
<script src="{% static 'js/script.js' %}"></script>
{% endblock %}
{% endblock %}

templates/food_cloud/search_restaurant.html
{% extends 'food_cloud/base_restaurant.html' %}
{% load staticfiles %}

{% block title_block %}
	Search
{% endblock %}

{% block body_block %}
	<div class="jumbotron p-4">
		<div class="container">
		<h1 class="jumbotron-heading">Search with food_cloud</h1>
		</div>
	</div>

	<div>
		<form class="form-inline"
			id="user-form"
			method="post"
			action="{% url 'food_cloud:search' %}">
			{% csrf_token %}

			<div class="form-group">
				<input class="form-control"
					type="text"
					size="50"
					name="query"
					id="query" 
					value="{{ query }}"/>
			</div>

			<button class="btn btn-primary"
				type="submit"
				name="submit">Search</button>
		</form>
	</div>
	<div>
		{% if result_list %}
			<h2>Results</h2>

			<div class="list-group">
				{% for result in result_list %}
					<div class="list-group-item">
						<h3 class="list-group-item-heading">
							<a href="{{ result.link }}">
								{{ result.title|safe|escape }}
							</a>
						</h3>
						<p class="list-group-item-text">
							{{ result.summary|safe|escape }}
						</p>
					</div>
				{% endfor %}
			</div>
		{% endif %}
	</div>
{% endblock %}